# Generated by Django 4.2.7 on 2023-11-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncategory',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='transactiontype',
            old_name='main_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transactiontype',
            old_name='transaction_type',
            new_name='transaction_type_name',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='sub_name',
        ),
    ]
