# Generated by Django 4.2.7 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='cashflow_category_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
