# Generated by Django 4.2.7 on 2023-11-20 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_type_id', models.CharField(choices=[('income_fixed', 'Inkomen vast'), ('income_variable', 'Inkomen variabel'), ('spendings_fixed', 'Uitgaven vast'), ('spendings_variable_planned', 'Uitgaven variabel gepland'), ('spendings_variable_unplanned', 'Uitgaven variabel ongepland')], max_length=30, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
                ('subtype_name', models.CharField(max_length=30)),
                ('is_planned', models.IntegerField()),
            ],
            options={
                'ordering': ['transaction_type_id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionVariable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.transactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPlanned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payment_term', models.CharField(max_length=255, null=True)),
                ('date_valid_from', models.DateField()),
                ('date_valid_up_including', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.transactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
