# Generated by Django 4.2.7 on 2023-11-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_transactiontype_transactionvariable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Cashflow',
        ),
        migrations.DeleteModel(
            name='CashflowType',
        ),
    ]
