# Generated by Django 4.2.7 on 2023-11-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_transactionplanned_date_valid_up_including'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionplanned',
            name='date_valid_up_including',
            field=models.DateField(null=True),
        ),
    ]
